language: haxe

os: linux
dist: trusty

haxe:
  - development
  - stable

install:
  - haxelib list

script:
  - haxe tests.neko.hxml

notifications:
  email:
    on_success: never
    on_failure: always